# script to build Jamoma on Travis-ci.org
# see : https://travis-ci.org/jamoma/Jamoma/

language: cpp
sudo: false
env:
  matrix:
  - ARCH=
  - ARCH=rpi
  # - ARCH=mingw-w64
os:
  - linux
  - osx
matrix:
  exclude:
  - os: osx
    env: ARCH=rpi
  # - os: osx
  #  env: ARCH=mingw-w64
  # allow_failures:
  # - os: linux
  #  env: ARCH=mingw-w64

before_install:
- "./script/depinstall.sh"

script:
- "./script/build.sh"

after_success:
- "./script/deploy-git.sh"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
